### ISSUE TITLE
Eval command does not work

### ISSUE THREAD

**Issue by pcomans** [swannodette/textmate-clojure#1]
The Eval command does not work with Clojure 1.2 and cake 0.4.3 (at least I believe it doesn't)
When I enter (+ 4 5) in Textmate and press cmd+shift+x, I get:
nil
textmate$escape_quotes.invoke(utils.clj:21)
textmate$escape_str.invoke(utils.clj:30)
textmate$get_selected_sexpr.invoke(utils.clj:220)
textmate$eval2620.invoke(eval.clj:11)
clojure.lang.Compiler.eval(Compiler.java:5424)
clojure.lang.Compiler.load(Compiler.java:5857)
clojure.lang.Compiler.loadFile(Compiler.java:5820)
clojure.lang.RT$3.invoke(RT.java:296)
cake.server$run_file.invoke(server.clj:96)
cake.server$create$fn__495.invoke(server.clj:135)
cake.contrib.server_socket$accept_fn$fn__195$fn__198.invoke(server_socket.clj:39)
cake.contrib.server_socket$accept_fn$fn__195.invoke(server_socket.clj:38)
clojure.lang.AFn.run(AFn.java:24)
java.lang.Thread.run(Thread.java:637)

Expected result should be 9

**Comment by swannodette** [comment]
I just tried this and it worked for me. Did you select the sexpr before running the command?

**Comment by swannodette** [comment]
I'm closing this since I believe this is resolved in textmate-clojure 0.1.0
